import OmiTheme
import SwiftUI

/// Cards for the App Insights and Try with Apps sections of a conversation
/// detail, plus the sheet that picks an app to reprocess with.
///
/// Split out of `ConversationDetailView` to keep that file under the
/// 1,500-line ratchet threshold; nothing here reaches back into it.

// MARK: - App Result Card

struct AppResultCard: View {
  let result: AppResponse
  let app: OmiApp?

  @State private var isExpanded = false

  var body: some View {
    VStack(alignment: .leading, spacing: OmiSpacing.sm) {
      // Header
      HStack(spacing: OmiSpacing.sm) {
        if let app = app {
          AsyncImage(url: URL(string: app.image)) { phase in
            switch phase {
            case .success(let image):
              image
                .resizable()
                .aspectRatio(contentMode: .fill)
            default:
              RoundedRectangle(cornerRadius: OmiChrome.elementRadius)
                .fill(OmiColors.backgroundTertiary)
            }
          }
          .frame(width: 32, height: 32)
          .clipShape(RoundedRectangle(cornerRadius: OmiChrome.elementRadius))

          VStack(alignment: .leading, spacing: OmiSpacing.hairline) {
            Text(app.name)
              .scaledFont(size: OmiType.body, weight: .medium)
              .foregroundColor(OmiColors.textPrimary)

            Text(app.author)
              .scaledFont(size: OmiType.caption)
              .foregroundColor(OmiColors.textTertiary)
          }
        } else {
          Image(systemName: "app.fill")
            .scaledFont(size: OmiType.subheading)
            .foregroundColor(OmiColors.textTertiary)
            .frame(width: 32, height: 32)
            .background(OmiColors.backgroundTertiary)
            .clipShape(RoundedRectangle(cornerRadius: OmiChrome.elementRadius))

          Text("App")
            .scaledFont(size: OmiType.body, weight: .medium)
            .foregroundColor(OmiColors.textPrimary)
        }

        Spacer()

        Button(action: { OmiMotion.withGated { isExpanded.toggle() } }) {
          Image(systemName: isExpanded ? "chevron.up" : "chevron.down")
            .scaledFont(size: OmiType.caption)
            .foregroundColor(OmiColors.textTertiary)
        }
        .buttonStyle(.plain)
      }

      // Content
      if isExpanded || result.content.count < 200 {
        Text(result.content)
          .scaledFont(size: OmiType.body)
          .foregroundColor(OmiColors.textSecondary)
          .textSelection(.enabled)
          .lineSpacing(4)
      } else {
        Text(result.content.prefix(200) + "...")
          .scaledFont(size: OmiType.body)
          .foregroundColor(OmiColors.textSecondary)
          .textSelection(.enabled)
          .lineSpacing(4)
      }

      // "Generated by" footer
      if let app = app {
        HStack(spacing: OmiSpacing.xs) {
          AsyncImage(url: URL(string: app.image)) { phase in
            switch phase {
            case .success(let image):
              image
                .resizable()
                .aspectRatio(contentMode: .fill)
            default:
              RoundedRectangle(cornerRadius: OmiChrome.stripRadius)
                .fill(OmiColors.backgroundTertiary)
            }
          }
          .frame(width: 16, height: 16)
          .clipShape(RoundedRectangle(cornerRadius: OmiChrome.stripRadius))

          Text("Generated by \(app.name)")
            .scaledFont(size: OmiType.caption)
            .foregroundColor(OmiColors.textTertiary)
        }
        .padding(.horizontal, OmiSpacing.sm)
        .padding(.vertical, OmiSpacing.xxs)
        .background(
          Capsule()
            .fill(OmiColors.backgroundTertiary.opacity(0.6))
        )
      }
    }
    .padding(OmiSpacing.md)
    .background(
      RoundedRectangle(cornerRadius: OmiChrome.smallControlRadius)
        .fill(OmiColors.backgroundSecondary)
    )
  }
}

// MARK: - Suggested App Card

struct SuggestedAppCard: View {
  let app: OmiApp
  let isLoading: Bool
  let onTap: () -> Void

  @State private var isHovering = false

  var body: some View {
    Button(action: onTap) {
      VStack(spacing: OmiSpacing.sm) {
        ZStack {
          AsyncImage(url: URL(string: app.image)) { phase in
            switch phase {
            case .success(let image):
              image
                .resizable()
                .aspectRatio(contentMode: .fill)
            default:
              RoundedRectangle(cornerRadius: OmiChrome.smallControlRadius)
                .fill(OmiColors.backgroundTertiary)
            }
          }
          .frame(width: 56, height: 56)
          .clipShape(RoundedRectangle(cornerRadius: OmiChrome.smallControlRadius))

          if isLoading {
            RoundedRectangle(cornerRadius: OmiChrome.smallControlRadius)
              .fill(Color.black.opacity(0.5))
              .frame(width: 56, height: 56)

            ProgressView()
              .scaleEffect(0.7)
              .tint(.white)
          }
        }

        Text(app.name)
          .scaledFont(size: OmiType.caption, weight: .medium)
          .foregroundColor(OmiColors.textPrimary)
          .lineLimit(1)
      }
      .frame(width: 80)
      .padding(.vertical, OmiSpacing.sm)
      .padding(.horizontal, OmiSpacing.sm)
      .background(
        RoundedRectangle(cornerRadius: OmiChrome.smallControlRadius)
          .fill(isHovering ? OmiColors.backgroundTertiary : OmiColors.backgroundSecondary)
      )
    }
    .buttonStyle(.plain)
    .disabled(isLoading)
    .onHover { isHovering = $0 }
  }
}

// MARK: - App Selector Sheet

struct AppSelectorSheet: View {
  let apps: [OmiApp]
  let isLoading: Bool
  let onSelect: (OmiApp) -> Void
  let onDismiss: () -> Void

  @State private var selectedAppId: String?

  var body: some View {
    VStack(spacing: 0) {
      // Header
      HStack {
        Text("Select App")
          .scaledFont(size: OmiType.subheading, weight: .semibold)
          .foregroundColor(OmiColors.textPrimary)

        Spacer()

        Button(action: onDismiss) {
          Image(systemName: "xmark.circle.fill")
            .scaledFont(size: OmiType.heading)
            .foregroundColor(OmiColors.textTertiary)
        }
        .buttonStyle(.plain)
      }
      .padding()

      Divider()
        .background(OmiColors.backgroundTertiary)

      // Apps list
      if apps.isEmpty {
        VStack(spacing: OmiSpacing.md) {
          Image(systemName: "square.grid.2x2")
            .scaledFont(size: OmiType.hero)
            .foregroundColor(OmiColors.textTertiary)

          Text("No Apps Available")
            .scaledFont(size: OmiType.body, weight: .medium)
            .foregroundColor(OmiColors.textSecondary)

          Text("Enable apps with memory capability to reprocess conversations")
            .scaledFont(size: OmiType.caption)
            .foregroundColor(OmiColors.textTertiary)
            .multilineTextAlignment(.center)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .padding()
      } else {
        ScrollView {
          LazyVStack(spacing: OmiSpacing.hairline) {
            ForEach(apps) { app in
              AppSelectorRow(
                app: app,
                isSelected: selectedAppId == app.id,
                isLoading: isLoading && selectedAppId == app.id
              ) {
                selectedAppId = app.id
                onSelect(app)
              }
            }
          }
          .padding(.horizontal, OmiSpacing.sm)
          .padding(.vertical, OmiSpacing.sm)
        }
      }
    }
    .frame(width: 320, height: 400)
    .background(OmiColors.backgroundPrimary)
  }
}

struct AppSelectorRow: View {
  let app: OmiApp
  let isSelected: Bool
  let isLoading: Bool
  let onSelect: () -> Void

  @State private var isHovering = false

  var body: some View {
    Button(action: onSelect) {
      HStack(spacing: OmiSpacing.md) {
        AsyncImage(url: URL(string: app.image)) { phase in
          switch phase {
          case .success(let image):
            image
              .resizable()
              .aspectRatio(contentMode: .fill)
          default:
            RoundedRectangle(cornerRadius: OmiChrome.smallControlRadius)
              .fill(OmiColors.backgroundTertiary)
          }
        }
        .frame(width: 44, height: 44)
        .clipShape(RoundedRectangle(cornerRadius: OmiChrome.smallControlRadius))

        VStack(alignment: .leading, spacing: OmiSpacing.hairline) {
          Text(app.name)
            .scaledFont(size: OmiType.body, weight: .medium)
            .foregroundColor(OmiColors.textPrimary)

          Text(app.author)
            .scaledFont(size: OmiType.caption)
            .foregroundColor(OmiColors.textTertiary)
        }

        Spacer()

        if isLoading {
          ProgressView()
            .scaleEffect(0.7)
        } else if isSelected {
          Image(systemName: "checkmark.circle.fill")
            .scaledFont(size: OmiType.heading)
            .foregroundColor(OmiColors.accent)
        }
      }
      .padding(.horizontal, OmiSpacing.md)
      .padding(.vertical, OmiSpacing.sm)
      .background(
        RoundedRectangle(cornerRadius: OmiChrome.smallControlRadius)
          .fill(isSelected || isHovering ? OmiColors.backgroundTertiary : Color.clear)
      )
    }
    .buttonStyle(.plain)
    .disabled(isLoading)
    .onHover { isHovering = $0 }
  }
}
